/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ChartType, DataModel, Param } from "@senx/discovery-widgets";
export namespace Components {
    interface DiscoveryPluginSensorGauge {
        "debug": boolean;
        "height": number;
        "options": Param | string;
        "resize": () => Promise<void>;
        "result": DataModel | string;
        "type": ChartType;
        "width": number;
    }
}
export interface DiscoveryPluginSensorGaugeCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLDiscoveryPluginSensorGaugeElement;
}
declare global {
    interface HTMLDiscoveryPluginSensorGaugeElement extends Components.DiscoveryPluginSensorGauge, HTMLStencilElement {
    }
    var HTMLDiscoveryPluginSensorGaugeElement: {
        prototype: HTMLDiscoveryPluginSensorGaugeElement;
        new (): HTMLDiscoveryPluginSensorGaugeElement;
    };
    interface HTMLElementTagNameMap {
        "discovery-plugin-sensor-gauge": HTMLDiscoveryPluginSensorGaugeElement;
    }
}
declare namespace LocalJSX {
    interface DiscoveryPluginSensorGauge {
        "debug"?: boolean;
        "height"?: number;
        "onDraw"?: (event: DiscoveryPluginSensorGaugeCustomEvent<void>) => void;
        "options"?: Param | string;
        "result"?: DataModel | string;
        "type"?: ChartType;
        "width"?: number;
    }
    interface IntrinsicElements {
        "discovery-plugin-sensor-gauge": DiscoveryPluginSensorGauge;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "discovery-plugin-sensor-gauge": LocalJSX.DiscoveryPluginSensorGauge & JSXBase.HTMLAttributes<HTMLDiscoveryPluginSensorGaugeElement>;
        }
    }
}
